# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/have-fun-learning-data',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/have-fun-learning-data',
                'lib_path': 'have_fun_learning_data'},
  'syms': {'have_fun_learning_data.core': {'have_fun_learning_data.core.foo': ('core.html#foo', 'have_fun_learning_data/core.py')}}}
